require("configs.options")
require("configs.autocmds")
require("configs.keymaps")
require("configs.lazy")
--require("configs.lualine-config")
require("configs.windline-config")
require("configs.telescope-config")
